### ISSUE TITLE
Allow permissions

### ISSUE THREAD

**Issue by FCuttaia** [gqqnbig/advanced-play-search#46]
Is there a way to show all the app that request authorization for precise GPS location?

Thanks

**Comment by gqqnbig** [comment]
![firefox_2020-05-19_01-19-07](https://user-images.githubusercontent.com/614159/82302757-e4111b00-996e-11ea-9825-6bf48028a3a8.png)

You can use the Allow Permissions filter to exclude or include apps requiring precise GPS location.

**Comment by FCuttaia** [comment]
Thanks @gqqnbig but i can't show in search bar all the app allowing precise location in the world. If i disallow all the permissions and only flag precise locationg gps the system doesn't show me any app. Could u help me please?

Moreover is there a way to disallow all permissions with a click and then to flag only some permissions from the list?

Thank you

**Comment by gqqnbig** [comment]
The permissions button was designed to filter out apps and encourages apps to use less permissions. 

That A permission is allowed means apps using this permissions will be in the search result; apps not using this permission will also be in the result.

That a permission is not allowed means apps using this permissions will not be in the result; apps not using this permission will be in the result.

Your requirement is different. I guess that A permission is allowed means apps using this permissions will be in the search result; apps not using this permission will not be in the result; TThat A permission is allowed means apps using this permissions will be in the search result; apps not using this permission will also be in the result.
that a permission is not allowed means apps using this permissions will be in the search result; apps not using this permission will also be in the result.

Can you elaborate more in what situation you need this feature? What tasks are you performing?

**Comment by FCuttaia** [comment]
Hi, my task is very simple. I have to find only the app that requires GPS precise position when a user install them in his smartphone.

**Comment by FCuttaia** [comment]
My business is linked to Big data and GPS positioning

**Comment by gqqnbig** [comment]
Do you want to see dummy apps requiring 500 permissions but doing nothing for you in your search? Are there more profound requirements?

**Comment by FCuttaia** [comment]
It could be useful  (for example) flagging only GPS permission from allow filter list, that system would show all apps that requires GPS permission regardless the presence or not of other permissions .

**Comment by gqqnbig** [comment]
lack required information
