### ISSUE TITLE
Sort (and filter) by price

### ISSUE THREAD

**Issue by TehJumpingJawa** [gqqnbig/advanced-play-search#68]
Google frequently gives away coupons for £3 off £5 spend.

As Google has no basket for buying multiple products together, and the vast majority of premium apps are <£5, a means of finding those few apps that are >=£5 is highly desirable.

**Comment by gqqnbig** [comment]
It's online. Please check https://play.gqqnbig.me/search?q=text%20editor&sort=fhl&ap=false

Please advise the wording if you like

```
Sort by:
Highest rating first
Least permissions first
Price highest first
etc.
```
or
```
Sort by:
Rating highest first
Permissions least first
Price highest first
etc.
```

**Comment by TehJumpingJawa** [comment]
Wow that was fast!
Awesome thanks!

I think the 2nd format is better, as it puts the article of interest (Price, Permissions, Rating, etc) at the start of each entry; not only does it allow for faster reading by the user, but it also keeps related entries next to one another.
